/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2022-10-24")
public class PrestoThriftNullableTableMetadata implements org.apache.thrift.TBase<PrestoThriftNullableTableMetadata, PrestoThriftNullableTableMetadata._Fields>, java.io.Serializable, Cloneable, Comparable<PrestoThriftNullableTableMetadata> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrestoThriftNullableTableMetadata");

  private static final org.apache.thrift.protocol.TField TABLE_METADATA_FIELD_DESC = new org.apache.thrift.protocol.TField("tableMetadata", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PrestoThriftNullableTableMetadataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PrestoThriftNullableTableMetadataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable PrestoThriftTableMetadata tableMetadata; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TABLE_METADATA((short)1, "tableMetadata");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TABLE_METADATA
          return TABLE_METADATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.TABLE_METADATA};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TABLE_METADATA, new org.apache.thrift.meta_data.FieldMetaData("tableMetadata", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PrestoThriftTableMetadata.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrestoThriftNullableTableMetadata.class, metaDataMap);
  }

  public PrestoThriftNullableTableMetadata() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrestoThriftNullableTableMetadata(PrestoThriftNullableTableMetadata other) {
    if (other.isSetTableMetadata()) {
      this.tableMetadata = new PrestoThriftTableMetadata(other.tableMetadata);
    }
  }

  @Override
  public PrestoThriftNullableTableMetadata deepCopy() {
    return new PrestoThriftNullableTableMetadata(this);
  }

  @Override
  public void clear() {
    this.tableMetadata = null;
  }

  @org.apache.thrift.annotation.Nullable
  public PrestoThriftTableMetadata getTableMetadata() {
    return this.tableMetadata;
  }

  public PrestoThriftNullableTableMetadata setTableMetadata(@org.apache.thrift.annotation.Nullable PrestoThriftTableMetadata tableMetadata) {
    this.tableMetadata = tableMetadata;
    return this;
  }

  public void unsetTableMetadata() {
    this.tableMetadata = null;
  }

  /** Returns true if field tableMetadata is set (has been assigned a value) and false otherwise */
  public boolean isSetTableMetadata() {
    return this.tableMetadata != null;
  }

  public void setTableMetadataIsSet(boolean value) {
    if (!value) {
      this.tableMetadata = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TABLE_METADATA:
      if (value == null) {
        unsetTableMetadata();
      } else {
        setTableMetadata((PrestoThriftTableMetadata)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TABLE_METADATA:
      return getTableMetadata();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TABLE_METADATA:
      return isSetTableMetadata();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PrestoThriftNullableTableMetadata)
      return this.equals((PrestoThriftNullableTableMetadata)that);
    return false;
  }

  public boolean equals(PrestoThriftNullableTableMetadata that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tableMetadata = true && this.isSetTableMetadata();
    boolean that_present_tableMetadata = true && that.isSetTableMetadata();
    if (this_present_tableMetadata || that_present_tableMetadata) {
      if (!(this_present_tableMetadata && that_present_tableMetadata))
        return false;
      if (!this.tableMetadata.equals(that.tableMetadata))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTableMetadata()) ? 131071 : 524287);
    if (isSetTableMetadata())
      hashCode = hashCode * 8191 + tableMetadata.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PrestoThriftNullableTableMetadata other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTableMetadata(), other.isSetTableMetadata());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableMetadata()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableMetadata, other.tableMetadata);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PrestoThriftNullableTableMetadata(");
    boolean first = true;

    if (isSetTableMetadata()) {
      sb.append("tableMetadata:");
      if (this.tableMetadata == null) {
        sb.append("null");
      } else {
        sb.append(this.tableMetadata);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (tableMetadata != null) {
      tableMetadata.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrestoThriftNullableTableMetadataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PrestoThriftNullableTableMetadataStandardScheme getScheme() {
      return new PrestoThriftNullableTableMetadataStandardScheme();
    }
  }

  private static class PrestoThriftNullableTableMetadataStandardScheme extends org.apache.thrift.scheme.StandardScheme<PrestoThriftNullableTableMetadata> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PrestoThriftNullableTableMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TABLE_METADATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.tableMetadata = new PrestoThriftTableMetadata();
              struct.tableMetadata.read(iprot);
              struct.setTableMetadataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PrestoThriftNullableTableMetadata struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tableMetadata != null) {
        if (struct.isSetTableMetadata()) {
          oprot.writeFieldBegin(TABLE_METADATA_FIELD_DESC);
          struct.tableMetadata.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrestoThriftNullableTableMetadataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PrestoThriftNullableTableMetadataTupleScheme getScheme() {
      return new PrestoThriftNullableTableMetadataTupleScheme();
    }
  }

  private static class PrestoThriftNullableTableMetadataTupleScheme extends org.apache.thrift.scheme.TupleScheme<PrestoThriftNullableTableMetadata> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrestoThriftNullableTableMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTableMetadata()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTableMetadata()) {
        struct.tableMetadata.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrestoThriftNullableTableMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.tableMetadata = new PrestoThriftTableMetadata();
        struct.tableMetadata.read(iprot);
        struct.setTableMetadataIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

