/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2022-10-24")
public class PrestoThriftSplitBatch implements org.apache.thrift.TBase<PrestoThriftSplitBatch, PrestoThriftSplitBatch._Fields>, java.io.Serializable, Cloneable, Comparable<PrestoThriftSplitBatch> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrestoThriftSplitBatch");

  private static final org.apache.thrift.protocol.TField SPLITS_FIELD_DESC = new org.apache.thrift.protocol.TField("splits", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField NEXT_TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("nextToken", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PrestoThriftSplitBatchStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PrestoThriftSplitBatchTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<PrestoThriftSplit> splits; // required
  public @org.apache.thrift.annotation.Nullable PrestoThriftId nextToken; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SPLITS((short)1, "splits"),
    NEXT_TOKEN((short)2, "nextToken");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SPLITS
          return SPLITS;
        case 2: // NEXT_TOKEN
          return NEXT_TOKEN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.NEXT_TOKEN};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SPLITS, new org.apache.thrift.meta_data.FieldMetaData("splits", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PrestoThriftSplit.class))));
    tmpMap.put(_Fields.NEXT_TOKEN, new org.apache.thrift.meta_data.FieldMetaData("nextToken", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PrestoThriftId.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrestoThriftSplitBatch.class, metaDataMap);
  }

  public PrestoThriftSplitBatch() {
  }

  public PrestoThriftSplitBatch(
    java.util.List<PrestoThriftSplit> splits)
  {
    this();
    this.splits = splits;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrestoThriftSplitBatch(PrestoThriftSplitBatch other) {
    if (other.isSetSplits()) {
      java.util.List<PrestoThriftSplit> __this__splits = new java.util.ArrayList<PrestoThriftSplit>(other.splits.size());
      for (PrestoThriftSplit other_element : other.splits) {
        __this__splits.add(new PrestoThriftSplit(other_element));
      }
      this.splits = __this__splits;
    }
    if (other.isSetNextToken()) {
      this.nextToken = new PrestoThriftId(other.nextToken);
    }
  }

  @Override
  public PrestoThriftSplitBatch deepCopy() {
    return new PrestoThriftSplitBatch(this);
  }

  @Override
  public void clear() {
    this.splits = null;
    this.nextToken = null;
  }

  public int getSplitsSize() {
    return (this.splits == null) ? 0 : this.splits.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<PrestoThriftSplit> getSplitsIterator() {
    return (this.splits == null) ? null : this.splits.iterator();
  }

  public void addToSplits(PrestoThriftSplit elem) {
    if (this.splits == null) {
      this.splits = new java.util.ArrayList<PrestoThriftSplit>();
    }
    this.splits.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<PrestoThriftSplit> getSplits() {
    return this.splits;
  }

  public PrestoThriftSplitBatch setSplits(@org.apache.thrift.annotation.Nullable java.util.List<PrestoThriftSplit> splits) {
    this.splits = splits;
    return this;
  }

  public void unsetSplits() {
    this.splits = null;
  }

  /** Returns true if field splits is set (has been assigned a value) and false otherwise */
  public boolean isSetSplits() {
    return this.splits != null;
  }

  public void setSplitsIsSet(boolean value) {
    if (!value) {
      this.splits = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public PrestoThriftId getNextToken() {
    return this.nextToken;
  }

  public PrestoThriftSplitBatch setNextToken(@org.apache.thrift.annotation.Nullable PrestoThriftId nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  public void unsetNextToken() {
    this.nextToken = null;
  }

  /** Returns true if field nextToken is set (has been assigned a value) and false otherwise */
  public boolean isSetNextToken() {
    return this.nextToken != null;
  }

  public void setNextTokenIsSet(boolean value) {
    if (!value) {
      this.nextToken = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SPLITS:
      if (value == null) {
        unsetSplits();
      } else {
        setSplits((java.util.List<PrestoThriftSplit>)value);
      }
      break;

    case NEXT_TOKEN:
      if (value == null) {
        unsetNextToken();
      } else {
        setNextToken((PrestoThriftId)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SPLITS:
      return getSplits();

    case NEXT_TOKEN:
      return getNextToken();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SPLITS:
      return isSetSplits();
    case NEXT_TOKEN:
      return isSetNextToken();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PrestoThriftSplitBatch)
      return this.equals((PrestoThriftSplitBatch)that);
    return false;
  }

  public boolean equals(PrestoThriftSplitBatch that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_splits = true && this.isSetSplits();
    boolean that_present_splits = true && that.isSetSplits();
    if (this_present_splits || that_present_splits) {
      if (!(this_present_splits && that_present_splits))
        return false;
      if (!this.splits.equals(that.splits))
        return false;
    }

    boolean this_present_nextToken = true && this.isSetNextToken();
    boolean that_present_nextToken = true && that.isSetNextToken();
    if (this_present_nextToken || that_present_nextToken) {
      if (!(this_present_nextToken && that_present_nextToken))
        return false;
      if (!this.nextToken.equals(that.nextToken))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSplits()) ? 131071 : 524287);
    if (isSetSplits())
      hashCode = hashCode * 8191 + splits.hashCode();

    hashCode = hashCode * 8191 + ((isSetNextToken()) ? 131071 : 524287);
    if (isSetNextToken())
      hashCode = hashCode * 8191 + nextToken.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PrestoThriftSplitBatch other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSplits(), other.isSetSplits());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSplits()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.splits, other.splits);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNextToken(), other.isSetNextToken());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNextToken()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nextToken, other.nextToken);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PrestoThriftSplitBatch(");
    boolean first = true;

    sb.append("splits:");
    if (this.splits == null) {
      sb.append("null");
    } else {
      sb.append(this.splits);
    }
    first = false;
    if (isSetNextToken()) {
      if (!first) sb.append(", ");
      sb.append("nextToken:");
      if (this.nextToken == null) {
        sb.append("null");
      } else {
        sb.append(this.nextToken);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (nextToken != null) {
      nextToken.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrestoThriftSplitBatchStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PrestoThriftSplitBatchStandardScheme getScheme() {
      return new PrestoThriftSplitBatchStandardScheme();
    }
  }

  private static class PrestoThriftSplitBatchStandardScheme extends org.apache.thrift.scheme.StandardScheme<PrestoThriftSplitBatch> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PrestoThriftSplitBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SPLITS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list218 = iprot.readListBegin();
                struct.splits = new java.util.ArrayList<PrestoThriftSplit>(_list218.size);
                @org.apache.thrift.annotation.Nullable PrestoThriftSplit _elem219;
                for (int _i220 = 0; _i220 < _list218.size; ++_i220)
                {
                  _elem219 = new PrestoThriftSplit();
                  _elem219.read(iprot);
                  struct.splits.add(_elem219);
                }
                iprot.readListEnd();
              }
              struct.setSplitsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NEXT_TOKEN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.nextToken = new PrestoThriftId();
              struct.nextToken.read(iprot);
              struct.setNextTokenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PrestoThriftSplitBatch struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.splits != null) {
        oprot.writeFieldBegin(SPLITS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.splits.size()));
          for (PrestoThriftSplit _iter221 : struct.splits)
          {
            _iter221.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.nextToken != null) {
        if (struct.isSetNextToken()) {
          oprot.writeFieldBegin(NEXT_TOKEN_FIELD_DESC);
          struct.nextToken.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrestoThriftSplitBatchTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PrestoThriftSplitBatchTupleScheme getScheme() {
      return new PrestoThriftSplitBatchTupleScheme();
    }
  }

  private static class PrestoThriftSplitBatchTupleScheme extends org.apache.thrift.scheme.TupleScheme<PrestoThriftSplitBatch> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrestoThriftSplitBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSplits()) {
        optionals.set(0);
      }
      if (struct.isSetNextToken()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSplits()) {
        {
          oprot.writeI32(struct.splits.size());
          for (PrestoThriftSplit _iter222 : struct.splits)
          {
            _iter222.write(oprot);
          }
        }
      }
      if (struct.isSetNextToken()) {
        struct.nextToken.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrestoThriftSplitBatch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list223 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.splits = new java.util.ArrayList<PrestoThriftSplit>(_list223.size);
          @org.apache.thrift.annotation.Nullable PrestoThriftSplit _elem224;
          for (int _i225 = 0; _i225 < _list223.size; ++_i225)
          {
            _elem224 = new PrestoThriftSplit();
            _elem224.read(iprot);
            struct.splits.add(_elem224);
          }
        }
        struct.setSplitsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.nextToken = new PrestoThriftId();
        struct.nextToken.read(iprot);
        struct.setNextTokenIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

