/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2022-10-24")
public enum PrestoThriftBound implements org.apache.thrift.TEnum {
  BELOW(1),
  EXACTLY(2),
  ABOVE(3);

  private final int value;

  private PrestoThriftBound(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static PrestoThriftBound findByValue(int value) { 
    switch (value) {
      case 1:
        return BELOW;
      case 2:
        return EXACTLY;
      case 3:
        return ABOVE;
      default:
        return null;
    }
  }
}
