apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-config
data:
  
  config.properties: |
    coordinator=false
    memory.heap-headroom-per-node=0.5GB
    query.max-memory=1GB
    query.max-memory-per-node=0.5GB
    query.max-total-memory-per-node=2GB
    discovery.uri=https://presto-coordinator:8443
    internal-communication.https.required=true
    internal-communication.https.keystore.path=/opt/presto/etc/presto-keystore.jks
    internal-communication.https.keystore.key=password
    node.internal-address-source=FQDN
    node.internal-address=presto-worker
    
  config-coordinator.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    memory.heap-headroom-per-node=0.5GB
    query.max-memory=1GB
    query.max-memory-per-node=0.5GB
    query.max-total-memory-per-node=2GB
    discovery-server.enabled=true
    discovery.uri=https://presto-coordinator:8443
    node.internal-address-source=FQDN
    node.internal-address=presto-coordinator
    http-server.http.enabled=false
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.https.keystore.path=/opt/presto/etc/presto-keystore.jks
    http-server.https.keystore.key=password
    internal-communication.https.required=true
    internal-communication.https.keystore.path=/opt/presto/etc/presto-keystore.jks
    internal-communication.https.keystore.key=password
    http-server.authentication.type=PASSWORD,CERTIFICATE
    

  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/opt/presto/etc/password.db

  access-control.properties: |
    access-control.name=file
    security.config-file=/opt/presto/etc/rules.json

  


    
  
    