apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  ports:
    # master rpc
    - name: hive
      port: 9083
      targetPort: 9083
  type: LoadBalancer
  selector:
    app: hive-metastore



---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hive-metastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image:  hive-metastore:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9083
          command:
            - /bin/bash
            - -c
          args: 
            - ${HIVE_HOME}/bin/schematool -initSchema -dbType mysql; ${HIVE_HOME}/bin/hive --service metastore
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: minio-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: minio-secrets   