---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
        - name: mc
          image:  minio/mc
          command: [ "sleep" ]
          args: [ "infinity" ]
          volumeMounts:
          - name: data
            mountPath: "/data/"
          env:
            - name: MINIO_USERNAME
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: minio-secrets
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: minio-secrets
        

      volumes:
        - name: data
          hostPath:
            # Change this path to the absolute path in your filesystem
            path: "/Users/angelica/O'Reilly/Learning and Operating Presto/Git/Learning-and-Operating-Presto/05/data_lakehouse/data" # Specify a path to a local drive or volume on the Kubernetes worker node
      
         