apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    # master rpc
    - name: minio-console
      port: 9090
      targetPort: 9090
    - name: minio-api
      port: 9000
      targetPort: 9000
  type: LoadBalancer
  selector:
    app: minio



---
apiVersion: v1
kind: ReplicationController
metadata:
  name: minio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image:  quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args: 
            - minio server /data --console-address :9090
          ports:
            - containerPort: 9090
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: minio-secrets
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: minio-secrets
        

       
         