apiVersion: v1
kind: Service
metadata:
  name: mysql-metastore
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-metastore
spec:
  selector:
    matchLabels:
      app: mysql-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-metastore
    spec:
      containers:
      - name: mysql
        image: arm64v8/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : admin
        - name: MYSQL_DATABASE
          value: metastore_db
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        ports:
        - containerPort: 3306
          name: mysql-metastore
        

