apiVersion: v1
kind: Service
metadata:
  name: presto-coordinator
spec:
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: presto-coordinator



---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-coordinator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
        - name: presto-coordinator
          image:  ahanaio/prestodb-sandbox:0.273.4
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: minio-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: minio-secrets

          #command:
          #  - /bin/bash
          #  - -c
          #args: 
          #  - /opt/presto/bin/launcher run
          ports:
            - containerPort: 8080
            - containerPort: 8887
          resources:
            requests:
              memory: "9Gi"
            limits:
              memory: "9Gi"
          volumeMounts:
            - name: etc
              mountPath: "opt/presto-server/etc"
              
            
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: etc
          hostPath:
            # Change this path to the absolute path in your filesystem
            path: "/Users/angelica/O'Reilly/Learning and Operating Presto/Git/Learning-and-Operating-Presto/05/data_lakehouse/conf" # Specify a path to a local drive or volume on the Kubernetes worker node
       
            
