apiVersion: v1
kind: Service
metadata:
  name: presto-coordinator
spec:
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: presto-coordinator



---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-coordinator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
        - name: presto-coordinator
          image:  prestodb:latest
          imagePullPolicy: Never
          command:
            - /bin/bash
            - -c
          args: 
            - /opt/presto/bin/launcher run
          ports:
            - containerPort: 8080
            - containerPort: 8889
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          volumeMounts:
            - name: config
              mountPath: "/opt/presto/etc/config.properties"
              subPath: config.properties
              
            - name: hive
              mountPath: "/opt/presto/etc/catalog/hive.properties"
              subPath: hive.properties
          
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: presto-config
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "config-coordinator.properties"
              path: "config.properties"
        - name: hive
          secret:
            secretName: presto-hive-secrets
            
