---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-worker
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
        - name: presto-worker
          image: prestodb:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          ports:
            - containerPort: 8889
          
          volumeMounts:
            - name: config
              mountPath: "/opt/presto/etc/config.properties"
              subPath: config.properties
              
            - name: pinot
              mountPath: "/opt/presto/etc/catalog/pinot.properties"
              subPath: pinot.properties
        
      volumes:
          # You set volumes at the Pod level, then mount them into containers inside that Pod
          - name: config
            configMap:
              # Provide the name of the ConfigMap you want to mount.
              name: presto-config
              # An array of keys from the ConfigMap to create as files
              items:
              - key: "config.properties"
                path: "config.properties"

          - name: pinot
            configMap:
              name: presto-config
              items:
              - key: "pinot.properties"
                path: "pinot.properties"