--- 
apiVersion: v1
stringData:
  mysql.properties: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mysql:3306
    connection-user=root
    connection-password=dbuser
  funcatalog.properties: |
    function-namespace-manager.name=mysql
    database-url=jdbc:mysql://mysql:3306/functionsdb?user=root&password=dbuser
    function-namespaces-table-name=example_function_namespaces
    functions-table-name=example_sql_functions
kind: Secret
metadata: 
  name: presto-mysql-secrets
type: Opaque