apiVersion: apps/v1
kind: Deployment
metadata:
  name: odbc-client
  labels:
    app: odbc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odbc-client
  template:
    metadata:
      labels:
        app: odbc-client
    spec:
      containers:
      - name: odbc-client
        image:  odbc-presto:latest
        imagePullPolicy: Never
        command: [ "sleep" ]
        args: [ "infinity" ]
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "2Gi"
        volumeMounts:
          - name: scripts
            mountPath: "/home/"
            

      volumes:
        - name: scripts
          hostPath:
            # Change this path to the absolute path in your filesystem
            path: "/Users/angelica/O'Reilly/Learning and Operating Presto/Code/04/odbc-client/scripts"
          