apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client
  labels:
    app: java-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-client
  template:
    metadata:
      labels:
        app: java-client
    spec:
      containers:
      - name: java-client
        image:  java-presto:latest
        imagePullPolicy: Never
        command: [ "sleep" ]
        args: [ "infinity" ]
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "2Gi"
        volumeMounts:
          - name: client
            mountPath: "/home/presto-client"
            

      volumes:
        - name: client
          hostPath:
            # Change this path to the absolute path in your filesystem
            path: "/absolute/path/to/Learning and Operating Presto/Code/04/java-client/client"
          