--- 
apiVersion: v1
stringData:
  mysql.properties: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mysql:3306
    connection-user=root
    connection-password=dbuser
kind: Secret
metadata: 
  name: presto-mysql-secrets
type: Opaque